### ISSUE TITLE
Dependencies for Build

### ISSUE THREAD

**Issue by TimBo93** [urukgit/WinTox#2]
Hi,

i just copied SharpTox.dll from last successful build of Toxy-Project into lib folder of WinTox. But i can't build WinTox. Can you write down which deps i need to build ?

Thank you,
TimBo

**Comment by peterbozso** [comment]
Hi! :)

You'll need libtox.dll: https://jenkins.libtoxcore.so/view/Libs/job/toxcore_win32_dll/
It's in the 'bin' folder of the zip. You have to copy it to the 'libs' folder of WinTox.
You'll also need to build the SharpToxPortable project (with x86 as target) and put the result (SharpTox Portable.dll) into 'libs' as well. After that you should be able to compile WinTox (x86).
Of course we plan to add these dependencies to NuGet later.

You are welcome! :)
Peter

**Comment by TimBo93** [comment]
Thank you for your response.
Where can i find SharpToxPortable?

NuGet would be fantastic.

Greets,
TimBo

**Comment by peterbozso** [comment]
Right here: https://github.com/Impyy/SharpTox/blob/master/SharpTox/SharpTox%20Portable.csproj ;)
You have to open it directly, it won't show up in SharpTox's solution if you open SharpTox.sln. After that, you should just switch to target x86, Build/Build Solution, and the result (SharpTox Portable.dll) should end up in SharpTox's 'bin' folder. That's what you'll need. :)

**Comment by TimBo93** [comment]
it works :+1:

**Comment by peterbozso** [comment]
Great! :)
