### ISSUE TITLE
No test release binaries

### ISSUE THREAD

**Issue by rodneyrod** [urukgit/WinTox#4]

**Comment by peterbozso** [comment]
At the moment our Jenkins build is failing. (https://jenkins.impy.me/job/OneTox%20x86/) If all goes as planned, it will fix itself as soon as the new AV code is merged into toxcore, and you'll be able to download the executable from the above link. Until then, you have to build OneTox for yourself.

**Comment by quininer** [comment]
@uruk 
Will OneTox support WP? Because I do not see on the WP build.

**Comment by rodneyrod** [comment]
@uruk I can't see any .exe files in that jenkins zip build

**Comment by alexbakker** [comment]
@rodneyrod There are not supposed to be any exe files in there. You have to run the powershell script to install OneTox. 

Please keep in mind that this build is very outdated though.

**Comment by alexbakker** [comment]
@quininer In the future, but not right now.

**Comment by rodneyrod** [comment]
@Impyy Is it possible to get a portable exe? So we can test this in environments where we don't have admin rights?

Also, what versions of Windows is this supposed to support?

**Comment by alexbakker** [comment]
@rodneyrod That's not possible, this is a WinRT application.

As noted in the README, this is made for the Universal Windows Platform, meaning it will run on the Windows 10 platform.

**Comment by rodneyrod** [comment]
@Impyy So no Win8 or WinRT support?

**Comment by peterbozso** [comment]
@rodneyrod No, sorry.

**Comment by rodneyrod** [comment]
Well, that's a slight disappointment considering the privacy issues surrounding Windows 10, but I guess WinTox is still around.

**Comment by peterbozso** [comment]
Yes, if you think about XwinTox, it's still here: https://github.com/JX7P/XwinTox
But WinTox (without the 'X') was the name of this project what we changed in order to lessen the confusion regarding these two clients. (https://github.com/uruk/OneTox/commit/98f228cfedcaf6b50173fd064cb5b3b9c0fc1355) It was almost the same time when we changed this project's target OS from Windows 8.+ to Windows 10. (https://github.com/uruk/OneTox/commit/1a660f6141ff01daf0951a7278b0d61eb6ccffb5)

**Comment by alexbakker** [comment]
> Well, that's a slight disappointment considering the privacy issues surrounding Windows 10, but I guess WinTox is still around.

If you're that concerned about privacy you shouldn't be using Windows in the first place. All of the telemetry stuff was backported to older versions of Windows as well.

One of the main reasons for moving to UWP is the API expansions it brought as well as the possibility of using the same codebase on every windows 10 device.

**Comment by rodneyrod** [comment]
There was another Tox client targeting specifically Windows, I remember installing it on Win7, you wouldn't happen to know which one that would be would it?

**Comment by alexbakker** [comment]
That would be WinTox, which is now called [uTox](https://github.com/notsecure/uTox) (how confusing, right?). It used to specifically target Windows but is now a cross platform application. There is also [qTox](https://github.com/tux3/qTox), which I would recommend personally.

**Comment by NoxNoctium** [comment]
Probably Toxy: https://github.com/Impyy/Toxy

**Comment by rodneyrod** [comment]
No, it wasn't uTox, qTox or Toxy, I specifically remember it was Windows only but it didn't use any of the Metro theming, unless I am thinking of Toxy before it got that side panel.
