### ISSUE TITLE
Unable to import any profile

### ISSUE THREAD

**Issue by cuihaoleo** [urukgit/WinTox#5]
I'm using build 327 build by jekins on Windows 10.

OneTox seem to be unable to load any profile. It says "Importing profile failed because of corrupted .tox file."

I've tried (encrypted and unencrypted) profiles exported by qTox and even OneTox itself. None works.

<img width="601" alt="default" src="https://cloud.githubusercontent.com/assets/889871/11582073/ec296056-9a84-11e5-8654-f56e44a48c8c.PNG">
.

**Comment by peterbozso** [comment]
Hey! :) We are aware of this problem, it's most likely due to a bug in SharpTox. I will take a better look at this next week. Thanks for testing OneTox! :)

**Comment by alexbakker** [comment]
You can blame me for that. I was supposed to look at this ages ago. I'll see if I have time this afternoon.

**Comment by alexbakker** [comment]
Should be fixed in https://github.com/Impyy/SharpTox/commit/926761cda249a19d29e8ac42ae4de771a4f885f9. Can you try the latest build?

**Comment by cuihaoleo** [comment]
Confirmed. It's able to import uncrypted profile now.

It seems there are still some bugs that crash OneTox. I'll keep testing :)

**Comment by peterbozso** [comment]
Thank you very much for you help! Any other observation is very welcome! :)
